# Generated by Django 4.2.30 on 2026-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principale', '0002_alter_client_id_alter_imagelogement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelogement',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
